### ISSUE TITLE
Links to Goettingen Crum scans

### ISSUE THREAD

**Issue by signinstranger** [KELLIA/dictionary#165]
This is a follow-up on #17. Bibliographic links for the Crum dictionary should now direct to the HTTPS instance of our CoptOT website: 

`https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=1`

It would be great, if you could also add the original TLA entry number to the query string, like so: 

`https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=313&tla=C3263`

Cheers!
Malte

**Comment by amir-zeldes** [comment]
Thanks for pointing this out Malte, we should be able to take care of this soon.

**Comment by m-linssen** [comment]
Hi Malte,

just butting in here, apologies.
I have a handful of links to the manuscriptroom as well, exactly for those entries that aren't in the CDO - I will change those to HTTPS for version 1.8 and up, which will be out in the next few weeks, along with the first part of my Commentary.
A request though: would it be possible to highlight the left or right page (a / b) when the link has those? E.g. https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=313a would give the 313a page a red frame or something?

Cheers,

Martijn Linssen

**Comment by amir-zeldes** [comment]
Implemented https + TLA ID parameter in 42fce7d and deployed to production. Leaving this open for @signinstranger and @m-linssen to discuss the highlighting suggestion which sounds nice (though if the CoptOT Crum has a repo somewhere that might be a better place to start a new issue)

**Comment by signinstranger** [comment]
> Implemented https + TLA ID parameter in [42fce7d](https://github.com/KELLIA/dictionary/commit/42fce7d1df0514e6c329f7537e08c4bb24bd53d2) and deployed to production. Leaving this open for @signinstranger and @m-linssen to discuss the highlighting suggestion which sounds nice (though if the CoptOT Crum has a repo somewhere that might be a better place to start a new issue)

Thank you, @amir-zeldes. The column highlighting is indeed something that I should have done right from the start. If you want, you can change the link structure to  
[https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=313a&tla=C3263](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=313a&tla=C3263)
 I'll try to add the highlighting feature tomorrow.

**Comment by m-linssen** [comment]
Excellent! I see that the a and b are accepted now.
@signinstranger, I agree with @amir-zeldes that discussing this in a CoptOT repo would be preferable, but I'm confused now: do you prefer the docID to go along with the link or not? I see that they both work. The links by me concern only a minute fraction of the total requests to CoptOT I presume, but these two publications will be the last ones for a good while, so it would be desirable to have them function for a long time

Thank you,

Martijn Linssen

**Comment by signinstranger** [comment]
> Excellent! I see that the a and b are accepted now.

Highlighting should work now for both columns: 

[https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=720a](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=720a)

[https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=720b](https://coptot.manuscriptroom.com/crum-coptic-dictionary/?pageID=720b)
> @signinstranger, I agree with @amir-zeldes that discussing this in a CoptOT repo would be preferable, but I'm confused now: do you prefer the docID to go along with the link or not?

No, the docID is obsolete.

**Comment by m-linssen** [comment]
Fine, I have removed the docID from my links - yet they still come along from the CDO GUI, I see

A minor issue still: you support lowercase a and b as well as uppercase - but either an A or a B both lead to highlighting the b-page of an entry.
I'll only supply lowercase parameters and AFAIC this can be closed but perhaps you'd like to make that behaviour consistent in any way

@signinstranger  and @amir-zeldes , thank you very much for this beautiful addition and the lightning speed with which it got applied :-B

**Comment by amir-zeldes** [comment]
I can implement a/b but keep in mind that entries can span multiple columns, and in fact multiple pages. So for example:

https://coptic-dictionary.org/entry.cgi?tla=C7550

This entry points (with different senses) to `802ab`, `802b-803a`, `CD 802b`. Would you like for these to always point to the first mentioned column? So in these cases: `802a`, `802b`, `CD 802b`? Or would you like me to retain "ab" so a big box can be drawn around both columns? I assume multiple page ranges in the link are not desired, right?

Let me know what the best option would be and I can add it.

**Comment by m-linssen** [comment]
Well,

I'm unsure more than 1 frame would be desired so I'd opt for 802a, 802b, 802b with the idea behind it all that it saves the reader from finding out where exactly his search must start - and the idea behind that is that the CDO so very nicely gives a precise page indication yet the coptOT never picked up on it before

So I'm very happy!

**Comment by amir-zeldes** [comment]
OK, this is now implemented in CDO based on the suggestion above. If it looks good to everyone, feel free to close this issue - thanks for implementing the highlighting!

**Comment by signinstranger** [comment]
Thank you, @amir-zeldes.
